export const INDIAN_COLLEGES = [
  // National Institutes
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Varanasi (BHU)",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Dhanbad (ISM)",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Karnataka (Surathkal)",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Nagpur",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Jaipur",
  "National Institute of Technology (NIT) Allahabad",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Surat",
  "National Institute of Technology (NIT) Bhopal",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Goa",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Hamirpur",
  "National Institute of Technology (NIT) Srinagar",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "Indian Institute of Information Technology (IIIT) Gwalior",
  "Indian Institute of Information Technology (IIIT) Jabalpur",
  "Indian Institute of Information Technology (IIIT) Kancheepuram",
  "Indian Institute of Information Technology (IIIT) Dharwad",
  "Indian Institute of Information Technology (IIIT) Guwahati",
  "Indian Institute of Information Technology (IIIT) Kalyani",
  "Indian Institute of Information Technology (IIIT) Kota",
  "Indian Institute of Information Technology (IIIT) Lucknow",
  "Indian Institute of Information Technology (IIIT) Manipur",
  "Indian Institute of Information Technology (IIIT) Nagpur",
  "Indian Institute of Information Technology (IIIT) Pune",
  "Indian Institute of Information Technology (IIIT) Ranchi",
  "Indian Institute of Information Technology (IIIT) Sonepat",
  "Indian Institute of Information Technology (IIIT) Sri City",
  "Indian Institute of Information Technology (IIIT) Tiruchirappalli",
  "Indian Institute of Information Technology (IIIT) Vadodara",
  "Indian Institute of Information Technology (IIIT) Una",

  // Major Gujarat Institutions (Requested + Prominent)
  "Ganpat University",
  "L.J. University",
  "Silver Oak University",
  "Gujarat Technological University (GTU)",
  "Gujarat University",
  "Maharaja Sayajirao University of Baroda (MSU)",
  "Nirma University",
  "Ahmedabad University",
  "Marwadi University",
  "Parul University",
  "RK University",
  "Indrashil University",
  "L.D. College of Engineering (LDCE), Ahmedabad",
  "Vishwakarma Government Engineering College (VGEC)",
  "Dharmsinh Desai University (DDU)",
  "Pandit Deendayal Energy University (PDEU)",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)",
  "Charotar University of Science and Technology (CHARUSAT)",
  "Birla Vishvakarma Mahavidyalaya (BVM)",
  "Government Engineering College (GEC), Bhavnagar",
  "Government Engineering College (GEC), Rajkot",
  "Government Engineering College (GEC), Surat",
  "Government Engineering College (GEC), Gandhinagar",
  "Government Engineering College (GEC), Modasa",
  "Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat",
  "Sarkhej-Gandhinagar Highway College (SSEC)",
  "Institute of Infrastructure Technology Research and Management (IITRAM)",
  "Sankalchand Patel University",
  "Uka Tarsadia University",
  "P P Savani University",
  "Navrachana University",
  "Atmiya University",
  "C.U. Shah University",
  "Rai University",
  "G L S University",
  "Anant National University",
  "Karnavati University",
  "Auro University",
  "Adani University",
  "ITM Vocational University",
  "Gokul Global University",
  "Indus University",
  "Darshan University",
  "Swarnim Startup & Innovation University",

  // Universities Across India (Major Government & Private)
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "University of Mumbai",
  "University of Calcutta",
  "University of Madras",
  "Anna University",
  "Osmania University",
  "University of Hyderabad",
  "Savitribai Phule Pune University",
  "Jadavpur University",
  "Kolkata University",
  "University of Rajasthan",
  "Panjab University",
  "Kurukshetra University",
  "Maharshi Dayanand University (MDU)",
  "Amity University",
  "Vellore Institute of Technology (VIT)",
  "SRM Institute of Science and Technology",
  "Manipal Academy of Higher Education (MAHE)",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "BITS Pilani, Goa Campus",
  "BITS Pilani, Hyderabad Campus",
  "Thapar Institute of Engineering and Technology",
  "Christ University, Bangalore",
  "Symbiosis International University",
  "Lovely Professional University (LPU)",
  "Chandigarh University",
  "Sharda University",
  "Galgotias University",
  "Shiv Nadar University",
  "OP Jindal Global University",
  "Ashoka University",
  "Plaksha University",
  "Bennett University",
  "Graphic Era University",
  "UPES Dehradun",
  "DIT University",
  "Manipal University Jaipur",
  "Alliance University",
  "Jain University",
  "PES University",
  "RV College of Engineering",
  "MS Ramaiah Institute of Technology",
  "BMS College of Engineering",
  "Chaitanya Bharathi Institute of Technology (CBIT)",
  "VNR Vignana Jyothi Institute of Engineering and Technology",
  "Vasavi College of Engineering",
  "Sathyabama Institute of Science and Technology",
  "Kalinga Institute of Industrial Technology (KIIT)",
  "Siksha 'O' Anusandhan (SOA)",
  "Vignan's Foundation for Science, Technology and Research",
  "Koneru Lakshmaiah Education Foundation (KL University)",
  "Gitam University",
  "Karunya Institute of Technology and Sciences",
  "Bharath Institute of Higher Education and Research",
  "Hindustan Institute of Technology and Science",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
  "Sastra University",
  "Kalvium",
  "Scaler School of Technology",
  "Newton School of Technology",

  // Management & Law
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Udaipur",
  "XLRI - Xavier School of Management",
  "FMS Delhi",
  "SPJIMR Mumbai",
  "MDI Gurgaon",
  "NMIMS University",
  "National Law School of India University (NLSIU)",
  "National Law University (NLU) Delhi",
  "NALSAR University of Law",
  "West Bengal National University of Juridical Sciences (WBNUJS)",

  // Arts, Commerce, others
  "St. Stephen's College, Delhi",
  "Lady Shri Ram College for Women",
  "Hindu College, Delhi",
  "Miranda House, Delhi",
  "Hansraj College, Delhi",
  "Ramjas College, Delhi",
  "SRCC, Delhi",
  "LSR, Delhi",
  "St. Xavier's College, Mumbai",
  "St. Xavier's College, Kolkata",
  "Loyola College, Chennai",
  "Presidency University, Kolkata",
  "Fergusson College, Pune",
  "Mithibai College, Mumbai",
  "Narsee Monjee College of Commerce and Economics",
  "Symbiosis College of Arts and Commerce",
  "Christ College, Rajkot",
  "St. Joseph's College, Bangalore",
  "Madras Christian College (MCC)",

  // Additional Colleges/Universities
  "Tezpur University",
  "Gauhati University",
  "Dibrugarh University",
  "Assam Don Bosco University",
  "Mizoram University",
  "Nagaland University",
  "Sikkim Manipal University",
  "Tripura University",
  "Patna University",
  "Magadh University",
  "Chanakya National Law University",
  "Central University of Bihar",
  "Ranchi University",
  "BIT Mesra",
  "Utkal University",
  "Sambalpur University",
  "Ravenshaw University",
  "Indira Gandhi National Open University (IGNOU)",
  "Delhi Pharmaceutical Sciences and Pharmaceutical University (DPSRU)",
  "Dr. B.R. Ambedkar University Delhi (AUD)",
  "Guru Gobind Singh Indraprastha University (GGSIPU)",
  "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
  "Netaji Subhas University of Technology (NSUT)",
  "Delhi Technological University (DTU)",
  "Jamia Hamdard",
  "Teri School of Advanced Studies",
  "South Asian University",
  "National Institute of Fashion Technology (NIFT)",
  "National Institute of Design (NID)",
  "Tata Institute of Social Sciences (TISS)",
  "Tata Institute of Fundamental Research (TIFR)",
  "Indian Statistical Institute (ISI)",
  "Chennai Mathematical Institute (CMI)"
].sort((a, b) => a.localeCompare(b));
